### ISSUE TITLE
Unable to save any images

### ISSUE THREAD

**Issue by jasoncharles** [some9000/StylePile#33]
Hi, 
Once an image is generated with Stylepile I am unable to save the image. Also, it does not display the summary image when processing in batches.

Thanks
Jason

**Comment by some9000** [comment]
Are you using the latest version of both StylePile and SD UI? Because, at least, saving should be fixed by now. Now the summary image may be a thing, because the image generation sequence works a little different here. I will try to look into it.

**Comment by jasoncharles** [comment]
Hi, 
I always have the latest version as I have scripted git pull on all extensions and automatic111 when I run the webui-user.bat.

The save error happens when I enable more then one "batch size" or "batch count". Then I can only save the first image. All the other images say error in red when I try to save them.

This does not happen when I do not use Stylepile.

Thanks
Jason

**Comment by ferocioustoast** [comment]
I have the same issue, I can only save the first image. I have the latest version of both.

Here is the error I get with batch count: 1 and batch size: 2, while trying to save the second image

```
Error completing request
Arguments: ('{"prompt": "Portrait of an attractive young lady,flower field background, square ratio", "all_prompts": ["Portrait of an attractive young lady,flower field background, square ratio"], "negative_prompt": "", "all_negative_prompts": [""], "seed": -1, "all_seeds": [-1], "subseed": -1, "all_subseeds": [-1], "subseed_strength": 0, "width": 512, "height": 512, "sampler_name": "Euler a", "cfg_scale": 7, "steps": 20, "batch_size": 1, "restore_faces": false, "face_restoration_model": null, "sd_model_hash": "81761151", "seed_resize_from_w": 0, "seed_resize_from_h": 0, "denoising_strength": null, "extra_generation_params": {}, "index_of_first_image": 0, "infotexts": ["Portrait of an attractive young lady,flower field background, square ratio\\nNegative prompt: watermark,signature\\nSteps: 20, Sampler: Euler a, CFG scale: 7, Seed: 1299813990, Size: 512x512, Clip skip: 2", "Portrait of an attractive young lady,flower field background, square ratio\\nNegative prompt: watermark,signature\\nSteps: 20, Sampler: Euler a, CFG scale: 7, Seed: 914774684, Size: 512x512, Clip skip: 2"], "styles": ["None", "None"], "job_timestamp": "20221230210947", "clip_skip": 2, "is_using_inpainting_conditioning": false}', [{'name': 'C:\\Users\\person\\AppData\\Local\\Temp\\tmp4630g7y6\\tmpmo4e5dm8.png', 'data': 'file=C:\\Users\\person\\AppData\\Local\\Temp\\tmp4630g7y6\\tmpmo4e5dm8.png', 'is_file': True}, {'name': 'C:\\Users\\person\\AppData\\Local\\Temp\\tmp4630g7y6\\tmpn8cxljhe.png', 'data': 'file=C:\\Users\\person\\AppData\\Local\\Temp\\tmp4630g7y6\\tmpn8cxljhe.png', 'is_file': True}], False, 1) {}
Traceback (most recent call last):
  File "C:\Users\person\stable-diffusion-webui\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\person\stable-diffusion-webui\modules\ui.py", line 140, in save_files
    fullfn, txt_fullfn = save_image(image, path, "", seed=p.all_seeds[i], prompt=p.all_prompts[i], extension=extension, info=p.infotexts[image_index], grid=is_grid, p=p, save_to_dirs=save_to_dirs)
IndexError: list index out of range

Traceback (most recent call last):
  File "C:\Users\person\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\person\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 983, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\person\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 913, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: tuple index out of range
```

**Comment by some9000** [comment]
Sorry for the super late reply. This should be fixed in the latest version (regular one, not Beta).
